{
  "apiVersion": 1,
  "datasources": [
    {
      "name": "Prometheus",
      "type": "prometheus",
      "url": "http://prometheus:9090",
      "access": "proxy",
      "isDefault": true
    },
    {
      "name": "PostgreSQL",
      "type": "postgres",
      "url": "postgres:5432",
      "access": "proxy",
      "database": "creator_platform",
      "user": "postgres",
      "secureJsonData": {
        "password": "postgres_secure_password_2025"
      },
      "jsonData": {
        "sslmode": "disable",
        "postgresVersion": 1500,
        "timescaledb": false
      }
    }
  ]
}